-- Distraktor-Laengenbias behoben (gefunden von Knut 2026-09-09): bei 67% der
-- 107 Multiple-Choice-Fragen war die richtige Antwort auch die (mit-)laengste
-- der vier Optionen (im Schnitt 83 vs. 50 Zeichen bei den Distraktoren) -- ein
-- klassischer Quiz-Tell, der Raten ohne Fachwissen beguenstigt. Fix betrifft
-- nur die 72 betroffenen Fragen: die drei falschen Optionen wurden inhaltlich
-- plausibel verlaengert (Begruendung/Zahl/Fachbegriff), die richtige Antwort
-- bleibt an jeder Frage wortwoertlich UND indexgleich unveraendert (die
-- A/B/C/D-Positionsbalance aus der Antwort-Buchstaben-Bias-Migration bleibt
-- damit unberuehrt). Automatisiert verifiziert: correct_option in jedem neuen
-- Array wortgleich vorhanden, keine Duplikate. Ergebnis: laengste-Option-Bias
-- sinkt von 67.3% auf 34.6% ueber den gesamten Fragenpool.
--
-- Herkunft/Details: Vault-Notiz Fragenkatalog, Korrektur-Log.

update public.questions set options = '["Generative AI trainiert nur mit gelabelten Daten (Supervised Learning), discriminative AI nur mit ungelabelten Daten (Unsupervised Learning)", "Generative AI kann neue Inhalte erzeugen (z. B. Text oder Bild), discriminative AI klassifiziert bzw. unterscheidet vorgegebene Inputs (z. B. Hund oder Katze auf einem Bild)", "Beide Begriffe bedeuten inhaltlich dasselbe, es sind lediglich unterschiedliche Marketing-Namen für denselben Modelltyp ohne technischen Unterschied im Trainingsziel", "Generative AI basiert ausschließlich auf der Transformer-Architektur, discriminative AI ausschließlich auf klassischen Algorithmen wie Entscheidungsbäumen"]'::jsonb where id = '2ed6bd1d-14a9-5ebb-b892-bf8e150bd4fd';
update public.questions set options = '["Nur die API kann strukturierten Output liefern, etwa als JSON mit festgelegten Feldern; das Chat-Interface liefert stets nur Fließtext", "Die API erhält bei jedem Aufruf nur den aktuellen Input; das Chat-Interface hängt im Hintergrund den bisherigen Gesprächsverlauf an", "Das Chat-Interface nutzt intern ein anderes, kleineres Sprachmodell als die API, um Antwortzeiten und Serverlast zu reduzieren", "Die API kann nur mit einem einzigen fest vorgegebenen Sprachmodell verwendet werden, ein Modellwechsel erfordert dabei einen komplett neuen Account"]'::jsonb where id = '6f0a8b60-cece-56da-9da5-8c9a167d5c72';
update public.questions set options = '["n8n lokal auf dem eigenen Rechner oder Server zu installieren und dort für interne Zwecke ohne Weiterverkauf zu betreiben", "n8n selbst als gehosteten Dienst weiterzuverkaufen bzw. Kunden Zugang zu einer eigenen n8n-Instanz als Produkt anzubieten", "n8n privat und kostenlos für eigene, nicht-kommerzielle Automatisierungsprojekte zu nutzen, solange keine Weiterverteilung stattfindet", "Den öffentlich auf GitHub verfügbaren Quellcode von n8n einzusehen, zu forken oder für eigene Studienzwecke zu analysieren"]'::jsonb where id = 'a9dacabc-58cb-5785-8033-04834e7fb362';
update public.questions set options = '["Trigger, Node und Output als Grundbausteine eines n8n-Workflows", "Zielorientierung (Goal), Aktion (Action), Werkzeuggebrauch/Reasoning (ReAct-Pattern)", "Login, Datenbank-Zugriff und API-Key als technische Voraussetzungen eines Agenten", "Geschwindigkeit, Kosten und Skalierbarkeit als Bewertungskriterien für die Wahl eines LLM-Anbieters"]'::jsonb where id = 'ff9b4d61-b605-50f6-9785-c70e7f490a91';
update public.questions set options = '["Die beiden Texte stammen laut Metadaten vom selben Autor", "Die beiden Texte besitzen exakt dieselbe Zeichenlänge", "Die beiden Texte widersprechen sich inhaltlich klar", "Die beiden Texte behandeln ähnliche/verwandte Themen"]'::jsonb where id = 'e9647e7e-d76e-5b21-9186-f34786891b1c';
update public.questions set options = '["Wichtig, Unwichtig, Fraglich (je nach Kontext)", "Public, Private, Confidential (Klassifizierung)", "Merken, Verwerfen, Zustimmung einholen", "Speichern, Löschen, Anonymisieren (DSGVO-basiert)"]'::jsonb where id = 'ccc18de0-c37e-51df-a0f5-4b52721fbad3';
update public.questions set options = '["Sprachmodelle verarbeiten Text tokenbasiert, wodurch Groß-/Kleinschreibung das Ergebnis beeinflussen kann", "Sprachmodelle wandeln jede Eingabe vor der internen Verarbeitung automatisch vollständig in Kleinschreibung um", "Ein separates Named-Entity-Recognition-Modul erkennt Firmennamen unabhängig vom eigentlichen Sprachmodell", "Die Retrieval-Komponente eines RAG-Systems normalisiert bei der Suche automatisch die Groß-/Kleinschreibung"]'::jsonb where id = 'a4e01dac-e813-54b0-a6c6-ec50b33a9adf';
update public.questions set options = '["Es entstehen bei wachsender Vektoranzahl automatisch doppelte Chunks, die den Index unnötig aufblähen", "Mehr irrelevanter Kontext verschlechtert das Signal-Rausch-Verhältnis (Nadel-im-Heuhaufen-Problem)", "Ältere Embedding-Modelle unterstützen technisch keine großen Datenmengen über eine feste Grenze hinaus", "Es verbessert bei wachsender Vektoranzahl automatisch die Precision, jedoch nicht den Recall der Suche"]'::jsonb where id = 'b31eb216-88a2-52b4-ae5d-006c1062aeec';
update public.questions set options = '["Sie prüft nur, ob der Text syntaktisch gültiges JSON ist, ohne ein Objekt zurückzugeben", "Sie wandelt einen Text-String, der wie ein JSON-Objekt aussieht, in ein echtes JSON/JavaScript-Objekt um", "Sie verschlüsselt sensible Felder im JSON-Objekt mit einem intern generierten Schlüssel", "Sie komprimiert das JSON-Objekt verlustfrei, um bei der nächsten Anfrage Tokens einzusparen"]'::jsonb where id = '72beeaaa-b2fe-5e45-8262-4dc99494ece7';
update public.questions set options = '["Weil Bildmodelle grundsätzlich keine Backpropagation zum Anpassen der Gewichte nutzen, LLMs dagegen ausschließlich über Backpropagation trainiert werden", "Fine-Tuning funktioniert bei beiden Modelltypen technisch identisch gut, nur die Rechenkosten und die Trainingsdauer unterscheiden sich deutlich", "Bei Bildklassifikation reicht oft das Nachtrainieren eines kleinen \"Kopfes\" auf gefrorenen Features; bei LLMs verändert Fine-Tuning tendenziell mehr Gewichte und kann bereits gelerntes Wissen überschreiben", "Bildmodelle sind grundsätzlich kleiner und deutlich günstiger zu trainieren, unabhängig davon, welcher Teil des Netzes angepasst wird"]'::jsonb where id = '3755c8da-b2ab-5c90-806a-e22b0ade99c2';
update public.questions set options = '["Weil es für die Kommunikation zwischen Agenten noch kein standardisiertes Protokoll wie MCP oder A2A gibt", "Weil ein falsch benannter Key in freier Text-Kommunikation keinen harten Fehler wirft und der Fehler sich unbemerkt einschleicht", "Weil Multi-Agenten-Systeme laut Kursaussage grundsätzlich keine Fehlerbehandlung wie Try/Catch-Blöcke unterstützen können", "Weil LLMs bei jeder Anfrage grundsätzlich deutlich langsamer rechnen als klassische, kompilierte Software"]'::jsonb where id = 'af2ccb84-34f7-5b11-97d9-c71961b98597';
update public.questions set options = '["Eine Kreditkarte bzw. ein hinterlegtes Zahlungsmittel, über das laufende API-Kosten eines Agenten automatisch abgerechnet werden", "Ein Datenbankeintrag mit der IP-Adresse und dem letzten Verbindungszeitpunkt eines Agenten zur Netzwerküberwachung", "Ein digitaler Ausweis, mit dem sich ein Agent kryptographisch gegenüber einer Firewall oder einem Gateway authentifiziert", "Eine maschinenlesbare Beschreibung, die zeigt, was ein Agent kann und wie andere mit ihm interagieren sollen — das Pendant zur Tool-Beschreibung bei MCP"]'::jsonb where id = 'a5f28a26-1ce6-512a-943f-d4aa40909c65';
update public.questions set options = '["MECE — Mutually Exclusive, Collectively Exhaustive", "KISS — Keep It Simple, Stupid (Vermeidung unnötiger Komplexität)", "DRY — Don''t Repeat Yourself (Vermeidung von Code-Duplizierung)", "YAGNI — You Aren''t Gonna Need It (kein Bau ungenutzter Features)"]'::jsonb where id = '1c59ed39-98eb-54ed-9f7e-25191e40608e';
update public.questions set options = '["Rate Limit, Auth Error, 404 und 500 als klassische HTTP-Statuscodes", "Syntax Error, Runtime Error, Logic Error und Compile Error der klassischen Programmierung", "Timeout, Nachrichtenverlust, teilweise Ausführung, Agent-Nichtverfügbarkeit", "Overfitting, Underfitting, Bias und Varianz beim Training von ML-Modellen"]'::jsonb where id = '4ec4fe28-914f-5ee7-b5e0-fda18998c5f9';
update public.questions set options = '["3 (geschlossen, offen, halboffen)", "5, inklusive separater Wartungsphase", "2 (Ein/Aus), ohne separaten Zwischenzustand", "4 (inkl. separatem Cooldown-Zustand)"]'::jsonb where id = '76bd378e-c9dc-504a-882a-393b8d3e4a19';
update public.questions set options = '["Alle drei Kriterien sind mathematisch exakt identisch definiert und unterscheiden sich in der Praxis nur durch ihre Namensgebung", "Alle Kriterien lassen sich bei ausreichend Rechenleistung und Trainingsdaten stets gleichzeitig erfüllen", "Unter bestimmten Bedingungen kann ein Modell nicht alle Kriterien gleichzeitig erfüllen, da sie sich gegenseitig ausschließen können", "Die drei Kriterien sind gesetzlich durch die DSGVO exakt definiert und für alle EU-Unternehmen verbindlich vorgeschrieben"]'::jsonb where id = '7f490ded-7ee5-582b-96c3-018a7c50e058';
update public.questions set options = '["Erst die komplette Testbatterie schreiben lassen, danach die KI das Feature bauen lassen, bis alle Tests grün sind", "Keine Tests schreiben und die Funktionalität stattdessen ausschließlich manuell durch Durchklicken der Oberfläche prüfen", "Tests und Feature gleichzeitig in einem einzigen Prompt bauen lassen, ohne zwischen beiden Schritten zu trennen", "Erst das komplette Feature bauen lassen und erst im Anschluss passende Tests dafür nachträglich schreiben"]'::jsonb where id = '4fc682c0-0014-5891-a927-43e2414ff535';
update public.questions set options = '["Weil das Sprachmodell frühere Chats grundsätzlich dauerhaft in einem persönlichen Langzeitgedächtnis pro Nutzer speichert", "Weil der Anbieter den kompletten Prompt-Text einfach dauerhaft und unbegrenzt im Arbeitsspeicher der GPU behält", "Für einen wiederholt genutzten, identischen Prompt-Präfix werden bereits berechnete interne Repräsentationen (Key/Value-Cache) wiederverwendet, statt sie neu zu berechnen", "Weil kürzere Prompts grundsätzlich automatisch günstiger abgerechnet werden, unabhängig von Wiederholung oder Inhalt"]'::jsonb where id = '2e1e426e-7754-5de4-b616-24cc78faaf27';
update public.questions set options = '["Er ist der häufigste Wert in der Verteilung, also der Modus mit der höchsten Auftrittshäufigkeit", "Er ist der höchste jemals gemessene Wert innerhalb der gesamten Verteilung, unabhängig von Ausreißern", "Er ist bei jeder Verteilung mathematisch immer exakt identisch mit dem arithmetischen Mittel", "Er ist der Wert, der die Verteilung in zwei exakt gleich große Hälften teilt, und wird von einzelnen Ausreißern kaum verzerrt"]'::jsonb where id = 'dd8e42cd-afc6-5d6c-84f5-bcbac85a0f7e';
update public.questions set options = '["dauerhaft gespeichert", "verschlüsselt abgelegt", "flüchtig / vergänglich", "komprimiert gespeichert"]'::jsonb where id = '9430815d-3a03-575d-85c6-a37c5b7b0eff';
update public.questions set options = '["Der EU AI Act ersetzt seit seinem vollständigen Inkrafttreten 2026 die DSGVO komplett und macht eigenständige Datenschutzregeln für Unternehmen überflüssig, da beide Regelwerke inhaltlich deckungsgleich seien", "Beide Regelwerke regeln inhaltlich dasselbe Themenfeld, sie unterscheiden sich laut dieser Sichtweise lediglich in Höhe und Berechnung der jeweiligen Strafrahmen bei Verstößen", "Der EU AI Act regelt ausschließlich öffentliche Behörden und staatliche Stellen, während die DSGVO ausschließlich für private Unternehmen und deren Kundendaten gilt", "Der EU AI Act regelt Risikoeinstufung und Aufsichtspflichten von KI-Systemen; die DSGVO regelt den Umgang mit personenbezogenen Daten, u. a. unter welchen Voraussetzungen sie auch außerhalb der EU übermittelt werden dürfen"]'::jsonb where id = '90d2d835-e1fa-58b4-843a-22a16d9daacb';
update public.questions set options = '["Bottle, ein sehr schlankes Micro-Framework ohne native Async-Unterstützung", "Tornado, ein asynchrones Framework primär für Netzwerk- und Socket-Anwendungen", "Django, ein umfangreiches Full-Stack-Framework mit eigenem ORM und Admin-Interface", "FastAPI"]'::jsonb where id = '3ef0d132-d161-5735-9fd4-2cc85fc666c5';
update public.questions set options = '["Supabase funktioniert dann technisch nur noch in Kombination mit Lovable als einzig unterstütztem Frontend", "Eine spürbar höhere Latenz bei jeder einzelnen Datenbankabfrage durch die zusätzliche Lovable-Zwischenschicht", "Die Daten werden dabei automatisch und ohne Möglichkeit zur Konfiguration unverschlüsselt gespeichert", "Man verliert die direkte Kontrolle über Schema und Migrationen und ist stark an Lovable gebunden (Vendor Lock-in)"]'::jsonb where id = 'ef66ad83-17b1-5e98-81f4-6b031132dd7b';
update public.questions set options = '["Einen physischen Server-Standort, an dem die Datenbank-Instanz gehostet wird", "Einen einzelnen Nutzer-Account mit eigenem Login und individuellen Zugriffsrechten", "Eine einzelne Datenbanktabelle innerhalb eines größeren, gemeinsam genutzten Schemas", "Eine Kundenfirma/Nutzergruppe, der mehrere einzelne Nutzer zugeordnet sind"]'::jsonb where id = '4170a8fe-e871-55fa-951a-208f4d593afe';
update public.questions set options = '["Automated Program Integration", "Application Process Identifier", "Application Programming Interface", "Artificial Programming Index"]'::jsonb where id = 'c37b8440-7d92-5ed8-a71f-d136aad451ea';
update public.questions set options = '["E-Mail-Adressen sind niemals eindeutig — mehrere Nutzer könnten zufällig dieselbe Adresse haben", "Nutzer können ihre E-Mail-Adresse ändern — ein vermeintlich stabiler Schlüssel ist es damit nicht wirklich", "Datenbank-Indizes auf Text-Spalten wie E-Mail sind technisch nicht möglich, nur numerische Spalten lassen sich indizieren", "E-Mail-Adressen können nicht als Fremdschlüssel (Foreign Key) in anderen Tabellen verwendet werden"]'::jsonb where id = 'dc18b86b-5d34-5c1d-8b55-5b5535598896';
update public.questions set options = '["20 Mio. € oder 4 % des weltweiten Jahresumsatzes (die DSGVO-Höchststrafe)", "35 Mio. € oder 7 % des weltweiten Jahresumsatzes (jeweils der höhere Betrag)", "1 % des EU-Umsatzes, angelehnt an die Bußgeldsystematik des Kartellrechts", "pauschal 10 Mio. € pro Verstoß, unabhängig von Unternehmensgröße oder Jahresumsatz"]'::jsonb where id = '68e7529b-3db2-555e-a427-a8d81a0da8b7';
update public.questions set options = '["Pseudonymisierte Daten gelten unter der DSGVO nicht mehr als personenbezogene Daten, sobald der Zuordnungsschlüssel getrennt gespeichert wird", "Es handelt sich um zwei Begriffe für denselben Vorgang, nur in unterschiedlichen Rechtsräumen (EU vs. USA) gebräuchlich", "Anonymisierung ist DSGVO-rechtlich nicht anerkannt, weshalb Unternehmen ausschließlich mit Pseudonymisierung arbeiten dürfen", "Bei Pseudonymisierung ist ein Rückschluss auf die Person über Zusatzwissen theoretisch noch möglich, bei Anonymisierung nicht mehr"]'::jsonb where id = '2913cc32-31da-56ef-8dee-d384a90bd82c';
update public.questions set options = '["Ein mathematisches Rahmenwerk, das über gezielt eingefügtes Rauschen begrenzt, wie stark sich ein Ergebnis durch das Hinzufügen oder Entfernen einer einzelnen Person im Datensatz verändern darf", "Ein Verfahren, das personenbezogene Daten durch irreversible Verschlüsselung vollständig unkenntlich macht, sodass technisch kein Rückschluss auf die Person mehr möglich ist", "Ein juristisches Prinzip aus Artikel 44 der DSGVO, das ausschließlich für Datenübermittlungen außerhalb der EU in Drittstaaten gilt, nicht für technische Anonymisierungsverfahren", "Ein Tool, das automatisch Namen und andere personenbezogene Daten aus PDF-Dokumenten mittels Texterkennung (OCR) entfernt, ohne den restlichen Datensatz zu verändern"]'::jsonb where id = 'a046262a-3754-5875-a33e-f3aa538454dc';
update public.questions set options = '["Workflows benötigen zwingend ein Sprachmodell, Agenten kommen dagegen komplett ohne LLM-Aufrufe aus", "Ein Workflow ist vorhersehbar/deterministisch, ein Agent handelt autonom und kann unvorhergesehene Dinge tun", "Agenten sind grundsätzlich günstiger im Betrieb, weil sie im Schnitt deutlich weniger Tokens pro Aufgabe verbrauchen", "Nur ein Agent kann mehrere Tools nutzen, ein Workflow ist auf ein einziges Tool beschränkt"]'::jsonb where id = 'c1cb9958-d96d-5fc5-9587-d1cafdb2d4d5';
update public.questions set options = '["Ältere Embedding-Modelle können große Datenmengen technisch nicht verarbeiten und brechen ab einer gewissen Dokumentanzahl ab", "Es führt automatisch zu doppelten, redundanten Chunks in der Vektordatenbank, was den Speicherbedarf unnötig erhöht", "Es macht die relevante Information (\"die Nadel\") in der wachsenden Datenmenge (\"Heuhaufen\") schwerer auffindbar", "Größere Datenbanken benötigen deutlich mehr Rechenleistung für den Chunking-Prozess selbst, unabhängig von der Suchqualität"]'::jsonb where id = '8d7bb551-7024-5325-8220-0999960bc858';
update public.questions set options = '["Teacher-Student-Setup (Knowledge Distillation)", "Reinforcement Learning per Belohnungssignal", "Prompt Engineering ohne Modelltraining", "Fine-Tuning auf einem kleineren Datensatz"]'::jsonb where id = '9ed12893-3e73-54bb-ba79-fc6b51977645';
update public.questions set options = '["Wie schnell ein Modell pro Sekunde Tokens generiert, ein reiner Geschwindigkeits-Benchmark unabhängig von der inhaltlichen Genauigkeit", "Wie viele Parameter ein Modell insgesamt besitzt, meist in Milliarden angegeben — ein reiner Größenindikator ohne Bezug zur Retrieval-Fähigkeit", "Ob ein Modell über ein langes Kontextfenster hinweg auch Information in der Mitte des Dokuments zuverlässig wiederfindet (Stichwort \"Lost in the Middle\"-Phänomen)", "Ob ein Modell zwischen zwei oder mehr Sprachen im selben Dokument zuverlässig unterscheiden und korrekt übersetzen kann, unabhängig von der Position im Text"]'::jsonb where id = '62b184df-06a4-5e00-acc2-11dc0435e375';
update public.questions set options = '["LLMs benötigen für jede PII-Erkennung ein separates Fine-Tuning, NER-Modelle dagegen nicht", "NER-Modelle sind gesetzlich für DSGVO-Konformität vorgeschrieben und müssen laut Verordnung zertifiziert werden", "NER-Modelle liefern grundsätzlich höhere Genauigkeit als jedes LLM, unabhängig von der Aufgabe", "NER-Modelle sind genau für diese eine Aufgabe trainiert, brauchen deutlich weniger Parameter/Rechenleistung und sind schneller/günstiger"]'::jsonb where id = '4c9429c4-e261-5489-a2c8-8dca623ba8d4';
update public.questions set options = '["Ein Router braucht immer einen Menschen im Loop zur Freigabe, ein Koordinator arbeitet dagegen vollständig autonom ohne diese Kontrolle", "Ein Koordinator kann nur einen einzigen Agenten aufrufen, ein Router beliebig viele", "Router und Koordinator sind im Kurs austauschbare Begriffe für exakt dasselbe Design-Pattern ohne funktionalen Unterschied", "Jeder Koordinator ist ein Router mit zusätzlicher Funktionalität (einer Feedback-Schleife), aber nicht jeder Router ist ein Koordinator"]'::jsonb where id = '07801d5f-129e-5940-b09b-d751ee1bef55';
update public.questions set options = '["Beide Ansätze seien im Ergebnis gleichwertig, die Wahl sei letztlich reine Geschmackssache ohne messbaren Unterschied", "Das System konnte sich trotz mehrerer Iterationen nicht entscheiden und gab am Ende keine klare Empfehlung ab", "RAG ist für die meisten Probleme die bessere Wahl, Feintuning eignet sich eher für Stil und Tonalität als für Faktenwissen", "Feintuning ist fast immer überlegen, weil es dauerhaft Tokenkosten spart und das Wissen direkt in die Modellgewichte einbrennt"]'::jsonb where id = '276d437b-2efa-50fe-883f-a46efbda6499';
update public.questions set options = '["RAM, SSD und Cloud-Storage als Hardware-Speicherebenen", "Agent Context Window (Buffer Memory), Flow State, persistierender Speicher", "Cache, Datenbank und Backup als klassische IT-Speicherhierarchie", "Short-Term-, Long-Term-, Working-Memory (aus der Psychologie)"]'::jsonb where id = 'cc2054a3-f001-5116-b570-33b1b4ce8b03';
update public.questions set options = '["Begrenzter Retry ohne Zeitdelta zwischen den einzelnen Versuchen", "Exponentielles Backoff (in der Praxis oft zusätzlich mit Jitter kombiniert)", "Circuit Breaker, der nach zu vielen Fehlern weitere Aufrufe vorübergehend blockiert", "Sofortiger Retry direkt nach dem Fehler, ganz ohne Wartezeit dazwischen"]'::jsonb where id = '8986731b-83bb-5dbc-a697-afdcb85a34fd';
update public.questions set options = '["Geoffrey Hinton", "Andrej Karpathy", "Sam Altman", "Yann LeCun"]'::jsonb where id = 'd9047bbe-5275-58af-bcee-b4df47e07da0';
update public.questions set options = '["pgEmbed", "pgSearch", "pgAI", "pgvector"]'::jsonb where id = 'f3991b10-f479-5913-85af-527188174295';
update public.questions set options = '["Dass der Transformer für die Sequenzverarbeitung auf Attention statt auf Convolutional Layers und Recurrence (RNNs) setzt", "Darauf, dass Nutzer beim Prompten volle Aufmerksamkeit brauchen, sonst sinkt die Antwortqualität spürbar", "Eine Anspielung darauf, dass Transformer ausschließlich mit einer einzigen Attention-Schicht auskommen", "Darauf, dass Aufmerksamkeit die einzige Ressource ist, die ein Modell beim Training kostet"]'::jsonb where id = '0973356e-d182-5af7-94a8-79e82a9bab3b';
update public.questions set options = '["Weil Perplexity-basierte Detektoren zwar zuverlässig funktionieren, aber aus Kostengründen nicht eingesetzt werden", "Weil KI-Anbieter aus Datenschutzgründen grundsätzlich keine Nutzertexte mit Trainingsdaten vergleichen dürfen und entsprechende Tools deshalb kaum verbreitet sind", "Weil Menschen KI-generierten Text mit über 90 % Genauigkeit zuverlässig erkennen können, nur automatisierte Tools scheitern", "Es gibt keinen allgemein zuverlässigen Detektor; selbst spezialisierte Klassifikatoren (z. B. von OpenAI) wurden mangels Genauigkeit wieder eingestellt"]'::jsonb where id = '340823a7-4aad-5e49-bf9c-039fb1212cd7';
update public.questions set options = '["Image Segmentation", "Named Entity Recognition (NER)", "Sentiment Analysis", "Zero-Shot Classification"]'::jsonb where id = '0027add3-2230-5100-a200-f0ed65d32755';
update public.questions set options = '["Eine Preisstufe (Pricing Tier), die die Kosten pro Rechenzentrum bestimmt", "Eine rein logische Softwaregrenze ohne eigene physische Infrastruktur", "Ein oder mehrere diskrete Rechenzentren mit eigener redundanter Strom- und Netzwerkversorgung innerhalb einer Region", "Eine Zone, die ausschließlich für europäische Kunden reserviert ist und in anderen Weltregionen nicht existiert"]'::jsonb where id = '9eed769c-f6b2-54e0-969d-5825ae4fb4c4';
update public.questions set options = '["Atom (GitHub)", "Sublime Text", "IntelliJ IDEA", "Visual Studio Code"]'::jsonb where id = 'b1d9aad3-5271-5631-b70e-2666b12887b2';
update public.questions set options = '["Weil Jailbreak-Erkennung im Kurs als kontextabhängiges Verständnisproblem beschrieben wurde, während PII-Erkennung als reines Klassifikationsproblem gilt, das auch ein spezialisierter Transformer ohne LLM lösen kann", "Weil kleine, spezialisierte Transformer-Modelle aufgrund ihrer geringen Parameterzahl grundsätzlich keinerlei kontextuelle Zusammenhänge erkennen können, egal wie sie trainiert wurden", "Weil LLM-Aufrufe für Jailbreak-Checks laut EU AI Act ausdrücklich gesetzlich vorgeschrieben sind, PII-Checks dagegen nicht, unabhängig vom eingesetzten Modellanbieter", "Weil PII-Erkennung im Betrieb deutlich teurer ist als Jailbreak-Erkennung, da dafür laut Kurs pro Anfrage deutlich mehr Rechenleistung und Speicher nötig sind"]'::jsonb where id = '9ca9a1c2-1967-5c2f-b4c4-99d9c0a1140d';
update public.questions set options = '["TypeScript wird zur Laufzeit direkt vom Browser interpretiert, ganz ohne vorherige Kompilierung zu JavaScript", "TypeScript = JavaScript mit optionaler statischer Typisierung (ein Compiler prüft Typen, auch wenn nicht jeder Typ explizit angegeben werden muss)", "TypeScript ist die ältere Sprache, JavaScript gilt als deren modernere Weiterentwicklung mit ähnlicher Syntax", "TypeScript ist eine komplett eigenständige Programmiersprache ohne jeden syntaktischen oder historischen Bezug zu JavaScript"]'::jsonb where id = '79c87eb1-3ed4-5cdb-8d8e-7f2ad7f81227';
update public.questions set options = '["Er sorgt automatisch für DSGVO-Konformität des gesamten Systems, ganz ohne weitere Maßnahmen", "Er verschlüsselt die komplette Datenbank inklusive aller Backups auf Festplattenebene", "Er erkennt und schwärzt personenbezogene Daten in Ein- oder Ausgaben, bevor sie weiterverarbeitet oder geloggt werden", "Er ersetzt die Notwendigkeit eines menschlichen Prüfers (Human in the Loop) vollständig"]'::jsonb where id = '63d2d95d-28de-5a70-a573-b216d31564ce';
update public.questions set options = '["Die Daten (meist als JSON), die beim Aufruf an den Webhook übergeben werden", "Die Anzahl der Knoten, aus denen ein n8n-Workflow beim Empfang des Webhook-Aufrufs besteht", "Die maximale Antwortzeit, die ein Server für die Verarbeitung des Webhook-Aufrufs einhalten muss", "Der HTTP-Header, der den Datentyp der Anfrage beschreibt, etwa Content-Type: application/json"]'::jsonb where id = '2da85511-9364-54e2-a93b-268fc13ce66f';
update public.questions set options = '["Das Modell ist sich bei jeder einzelnen Token-Vorhersage vollständig sicher, unabhängig vom tatsächlichen Trainingskorpus", "Das Modell arbeitet besonders langsam, weil die Inferenz mit zusätzlichen Rechenschritten pro Token belastet wird", "Das Modell sagt die tatsächlich beobachtete Tokenfolge im Mittel gut vorher (ein Maß für Vorhersagbarkeit, nicht direkt für Textqualität)", "Das Modell kostet besonders viel pro Token, weil die Perplexity direkt in die Abrechnung der API einfließt"]'::jsonb where id = 'cdfd07e7-e372-597f-b0b9-e285299a58fe';
update public.questions set options = '["Ein Agent baut sich seinen Pfad vom Trigger zum Ziel selbst; beim Workflow legt der Mensch die Struktur vorher fest", "Ein Workflow läuft grundsätzlich nur einmal pro Trigger, während ein Agent dauerhaft und ohne Unterbrechung im Hintergrund weiterläuft", "Ein Workflow kann grundsätzlich keine KI-Knoten enthalten, während ein Agent ausschließlich aus KI-Knoten ohne klassische Logik besteht", "Ein Agent ist im Gegensatz zum Workflow immer deterministisch und liefert bei gleichem Input garantiert dasselbe Ergebnis"]'::jsonb where id = '79eb7557-3341-5dd6-8198-b9fa9ad361c2';
update public.questions set options = '["Reasoning And Grounding (ein Verfahren, das Schlussfolgerungen direkt in den Modellgewichten verankert)", "Rule-based Agent Gateway (eine feste Regelschicht, die Agentenanfragen vor der Verarbeitung filtert)", "Random Access Generator (ein Verfahren, das zufällig auf Trainingsdaten zugreift statt sie gezielt zu indexieren)", "Retrieval Augmented Generation"]'::jsonb where id = '0a04aaf7-b32b-54c7-9d2f-4b7d0b4d3803';
update public.questions set options = '["Generative Pretrained Transformer", "Guided Prompt Technology (ein Verfahren, das Prompts automatisch anhand fester Vorlagen strukturiert)", "General Purpose Tool (eine Bezeichnung für universell einsetzbare Software ohne KI-Bezug)", "Global Processing Terminal (ein zentraler Server, der weltweit verteilte Rechenanfragen bündelt)"]'::jsonb where id = '0d5b8ff7-fdc0-5cf9-b272-b2b768919ed6';
update public.questions set options = '["Query Decomposition (das Zerlegen einer komplexen Anfrage in mehrere einfachere Teilfragen vor der Suche)", "Chain-of-Thought (das schrittweise Ausformulieren von Zwischengedanken vor der finalen Antwort)", "Re-Ranking (das nachträgliche Neusortieren bereits gefundener Suchergebnisse nach Relevanz)", "HyDE (Hypothetical Document Embeddings)"]'::jsonb where id = '55a8f9b5-1764-5e2c-af6a-e15cfb1d4706';
update public.questions set options = '["Ein einzelnes, kleineres Text-Segment eines Dokuments, das separat vektorisiert und durchsucht wird", "Ein komplettes Dokument, das unverändert und ohne jede Aufteilung in die Vektordatenbank geladen wird", "Der System-Prompt, der dem LLM vor jeder einzelnen Anfrage zusätzlich zum Nutzertext übergeben wird", "Ein Cache, der häufig gestellte Fragen samt Antworten zwischenspeichert, um die Vektorsuche zu umgehen"]'::jsonb where id = '5aea946e-0219-525c-9a6d-508a578fdd26';
update public.questions set options = '["Die Kosinus-Ähnlichkeit reduziert sich dann auf ein einfaches Skalarprodukt, effizienter berechenbar (GPU-freundlich)", "Weil längere, nicht normierte Vektoren deutlich mehr Speicherplatz in der Vektordatenbank benötigen würden", "Eine willkürliche Konvention aus der Frühzeit der Embedding-Modelle, ohne echten technischen Hintergrund", "Weil sich sonst Embeddings unterschiedlicher Modelle grundsätzlich nicht in derselben Vektordatenbank ablegen ließen"]'::jsonb where id = 'db862c78-0912-54e1-b5b5-75238c818d32';
update public.questions set options = '["Man fragt das Modell in mehreren Nachrichten hintereinander wiederholt nach seiner internen Modellversion und den Trainingsdaten", "Man schreibt ganz direkt und unverschlüsselt den Satz \"ignoriere alle vorherigen Anweisungen\" an den Anfang der Nachricht", "Man übersetzt den kompletten Systemprompt in eine andere Sprache, um Filter zu umgehen, die nur Deutsch prüfen", "Man tarnt die eigentliche Anfrage als Kinderschutz-Anliegen, um an dieselbe verbotene Information zu kommen"]'::jsonb where id = '5e90a87a-bad8-54cd-a538-2d201655e8da';
update public.questions set options = '["Die Verbindung wurde durch eine Firewall oder einen Proxy-Server aktiv blockiert, bevor sie den Zielserver erreicht", "Ein Server-Fehler, für den ausschließlich die Backend-Infrastruktur verantwortlich ist, nicht der Client", "Ein Fehler auf Client-Seite (z. B. eine ungültige oder fehlerhafte Anfrage)", "Die Anfrage wurde erfolgreich angenommen und wird asynchron im Hintergrund weiterverarbeitet, das Ergebnis kommt später"]'::jsonb where id = '426ce262-910a-5b19-a244-56571fe6323f';
update public.questions set options = '["Weil MCP-Server aus Sicherheitsgründen ausschließlich verschlüsselte, mit TLS signierte Anfragen akzeptieren", "Weil der MCP-Server die Anfrage nur korrekt verarbeiten kann, wenn sie dem vom Tool definierten Schema (Parameter-Namen und -Typen) entspricht", "Weil der MCP-Server ohne strukturierten Input technisch keine Response mehr an den aufrufenden Agenten zurückliefern kann", "Weil sonst die Tool-Beschreibung samt Namen und Kurzerklärung beim nächsten Serverstart nicht mehr geladen werden kann"]'::jsonb where id = 'b295b623-0c92-595b-8521-a6bb43a42c8e';
update public.questions set options = '["Mutually Exclusive, Collectively Exhaustive", "Multi Endpoint Communication Exchange (ein Protokoll für den Datenaustausch zwischen mehreren API-Endpunkten)", "Maximally Exact, Clearly Encoded (ein Kriterium für die präzise Formulierung von Kategorienamen)", "Modular Efficient Category Engine (eine Softwarekomponente, die Router-Kategorien automatisch generiert)"]'::jsonb where id = 'bb00553c-0988-5c51-b072-02831a3b7187';
update public.questions set options = '["Ein Banktresor mit mehreren Schlüsseln, zu dem nur autorisierte Agenten nach Prüfung Zugang erhalten", "Eine Blackbox, die niemand einsehen kann, weil ihr Inhalt ausschließlich modellintern verarbeitet wird", "Ein privates Tagebuch, das nur ein einzelner Agent lesen und beschreiben darf, ohne Zugriff der anderen", "Ein öffentlicher Park bzw. Brunnen, den alle nutzen dürfen, der aber durch einen einzelnen Agenten \"vergiftet\" werden kann"]'::jsonb where id = '5f9d1657-6749-5b5c-b40c-a87310de8927';
update public.questions set options = '["Ein bezahlter Peer-Review-Journal-Verlag, der Paper erst nach kostenpflichtiger Begutachtung veröffentlicht", "Ein Code-Repository, das ausschließlich für den Austausch von Wettbewerbslösungen im Machine Learning gedacht ist", "Eine kostenlose Preprint-Bibliothek, auf der Forscher Paper vor der Peer-Review-Veröffentlichung hochladen können", "Ein privates, zugangsbeschränktes Preprint-Archiv nur für Mitarbeiter großer Tech-Konzerne wie Google oder OpenAI"]'::jsonb where id = '3a16d98a-0f16-58cf-9f88-8c15fef56845';
update public.questions set options = '["Es bezeichnete ausschließlich das automatische Retry-Verhalten eines Agenten bei fehlgeschlagenen API-Aufrufen", "Es war eine komplett neue, in der Forschung bisher unbekannte Technik ohne Bezug zu bestehenden Patterns", "Es war im Kern das bereits bekannte ReAct-Pattern (Reasoning + Acting) unter neuem Namen", "Es war ein Fachbegriff aus der Schleifenoptimierung in Python, der die Laufzeit von for-Schleifen verbessert"]'::jsonb where id = '216e36af-dd6b-533d-be6d-c01cabff0a1e';
update public.questions set options = '["Von der Anzahl der Dokumente in beiden Jahrgängen und dem Rauschen (der Streuung) innerhalb der Jahrgänge", "Von der Reihenfolge, in der die Dokumente beim Indexieren eingelesen und verarbeitet werden", "Ausschließlich vom verwendeten Embedding-Modell, unabhängig von Dokumentanzahl oder Streuung", "Ausschließlich von der Sprache der Dokumente, da unterschiedliche Sprachen verschiedene Vektorräume erzeugen"]'::jsonb where id = 'a725e8bb-656e-5999-9d5d-8545c2fa8bdb';
update public.questions set options = '["Weil die AUC bei stark unausgewogenen Klassen, etwa 99 % Negativbeispielen, mathematisch grundsätzlich nicht berechenbar ist", "Weil die AUC sich ausschließlich auf den Trainingsdaten berechnen lässt und grundsätzlich keine Aussage über neue, ungesehene Daten erlaubt", "Weil man sich im echten Einsatz auf genau einen Schwellenwert festlegen muss — die AUC mittelt aber auch über Schwellenbereiche, die praktisch nie verwendet werden", "Weil sich die AUC technisch nur berechnen lässt, wenn beide Klassen exakt gleich häufig vorkommen, also bei einer 50/50-Verteilung"]'::jsonb where id = '6b456130-ea2d-5bc0-bfb5-fed061e6d98a';
update public.questions set options = '["Eine Tabelle mit Nutzer-ID und \"legitimiert bis\"-Datum, das jeder Workflow vor der Ausführung über einen Gatekeeper prüft", "Es wird ausschließlich die IP-Adresse des Nutzers gespeichert und bei jedem Aufruf gegen eine Whitelist geprüft", "Ein einmaliges Passwort bei der Registrierung, das danach nie wieder abgefragt oder erneut geprüft wird", "Der Login-Bildschirm allein reicht als Nachweis, danach wird die Berechtigung im weiteren Workflow nicht mehr geprüft"]'::jsonb where id = '6d883280-4ae9-5e89-a58e-2277a452c42e';
update public.questions set options = '["Nur wenn der Entschlüsselungs-Key technisch getrennt und niemals auf demselben Nicht-EU-Server gespeichert wird", "Gar nicht, ein Serverstandort außerhalb der EU ist unter der DSGVO ausnahmslos und ohne jede Ausnahme verboten", "Nur mit der ausdrücklichen und separat eingeholten Einwilligung jeder einzelnen betroffenen Person", "Wenn eine der in Kapitel V DSGVO vorgesehenen Grundlagen greift, z. B. ein EU-Angemessenheitsbeschluss für das Zielland oder Standardvertragsklauseln"]'::jsonb where id = '903ad320-e660-50b8-a778-d3346e01a4fa';
update public.questions set options = '["Bulk-Calls sind grundsätzlich schneller in der Verarbeitung, kosten dafür aber einen deutlichen Preisaufschlag", "Bulk-Calls kosten ca. 50 % weniger, sind dafür aber asynchron und können je nach Auslastung deutlich länger dauern", "Bulk-Calls kosten genauso viel wie Echtzeit-Calls, sparen dem Anbieter aber intern Rechenzeit und Serverlast", "Bulk-Calls liefern eine spürbar schlechtere Modellqualität, weil ein kleineres Modell im Hintergrund verwendet wird"]'::jsonb where id = '8897efd1-54a6-5255-88e3-a9009213102a';
update public.questions set options = '["PowerShell wird von Microsoft nicht mehr weiterentwickelt und erhält seit 2024 keine Sicherheitsupdates mehr", "PowerShell kann grundsätzlich keine Git-Befehle ausführen, da das Git-Binary nicht kompatibel ist", "PowerShell ist ausschließlich für die Server-Administration gedacht, nicht für die Softwareentwicklung", "Weil Claude Code am besten mit Bash-artigen Shells zusammenarbeitet, wie sie unter Linux/macOS Standard sind"]'::jsonb where id = 'd9e32ae8-447a-55ff-b360-ec860900f004';
update public.questions set options = '["Änderungen werden automatisch nach 30 Tagen gelöscht, um die Datenbank schlank zu halten", "Nur ein einzelner Admin-Account darf Einträge überhaupt ändern, alle anderen Nutzer sehen nur Lesezugriff", "Einträge können von jedem Nutzer beliebig und ohne weitere Protokollierung gelöscht werden", "Einträge bleiben editierbar; Löschen erzeugt stattdessen einen Storno-Eintrag, alles bleibt in einer durchgängigen Historie nachvollziehbar"]'::jsonb where id = 'cec6ee2f-356a-5403-ae14-da247042566e';
update public.questions set options = '["Weil man ohne Kennzeichnung sonst nicht merken würde, dass man mit einer KI statt einem Menschen spricht", "Weil KI-Stimmen ohne Kennzeichnung sonst automatisch rechtlich als Werbung im Sinne des Wettbewerbsrechts gelten", "Weil ansonsten jede Telefonaufzeichnung automatisch als personenbezogene Daten nach DSGVO gelten würde", "Weil ohne Kennzeichnung die zuständigen Aufsichtsbehörden formal keine Bußgelder mehr verhängen dürften"]'::jsonb where id = 'fb0cfd86-429c-55ed-b830-9e4a7c059f43';
update public.questions set options = '["Nur die Output-Filterung ist laut EU AI Act gesetzlich vorgeschrieben, die Input-Validierung bleibt freiwillig", "Es gibt technisch keinen Unterschied, beide Prüfungen laufen über denselben Filtermechanismus", "Ein Angriff kann entweder direkt in der Nutzereingabe stecken oder erst über einen manipulierten Werkzeug-/Tool-Output ins System gelangen", "Input-Validierung ist ausschließlich bei Sprachmodellen mit mehr als 70 Milliarden Parametern überhaupt nötig"]'::jsonb where id = '19eae144-0d48-5c20-a5a0-f1ce5e2c4be1';
